### ISSUE TITLE
Convert all StackTrace printing to create a log file

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartParking#11]
Currently, when an exception is thrown, the StackTrace is printed in the console. 
I was requested to change that into a log file. 
This issue will be closed when all calls to PrintStackTrace in the code are exchanged with said file creation.

**Comment by Shahar-Y** [comment]
OK. Seems like I misunderstood the task at hand a bit. I thought all I had to do is to create log files containing the stack trace printings when an error occurs. Apparently, the log file needs to be more informative, but I'm not sure how. 
@TomPalny , could you please specify more about this, or would you prefer if we talked about it in our meeting on Sunday? Maybe I should ask Yossi?

**Comment by TomPalny** [comment]
I'll get back to you with more info

בתודה,
תום

**Comment by TomPalny** [comment]
Hi guys,
Regarding recovery from exceptions:
The requirement is to be able to recover as gracefully as possible with
remaining inside the app at all cost (no crash that throws out of the app,
obviously).
So, whenever there's a stack-trace produced in the case of exceptions, you
need to convert it (or parse it) to something more readable that contains
the relevant information to the exception. Save it in a pre-defined place,
call it what you wish - logfile, exception log file, notify the user in the
app about the exact exception, where the error log was saved, and offer
context-related options.
If the exception was opening a file in use, write it in the message and
give a button that offers to retry or cancel. If the exception is no
internet connection, or timed-out request, give the user a message with the
option to stop or retry. If the worst has happened, null pointer exception
(which should not happen, but might) we need to be able to recover from
that like restart the window/app/service etc. and to point the user to the
location of the stack-trace log that was saved.
I hope that answers your question

בתודה,
תום

**Comment by TomPalny** [comment]
Yossi Gil's suggestion:
יש כמה גישות: הסטנדרטית, היא למצוא ספריה של לוגים, ולהשמש בה. יש כמה אלו
סטנדרטיות ונוחות. אפשר גם לממש משהו כזה ידנית, אבל קטן יותר. יש מימוש שלי
שאפשר לגנוב: המחלקות monitor ו fault בפרויקט הספרטניזציה.

בתודה,
תום

**Comment by zahimizrahi** [comment]
I recommend using Facade framework - https://www.slf4j.org/ 

try to check this out (and if we use it, make  a wiki about this as well)

**Comment by zahimizrahi** [comment]
there isn't much stackTrace since we moved to ionic, so this issue isn't relevant.
