### ISSUE TITLE
How to write an issue in "Final" 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#114]
This issue is a template for the issue our testers will open in "Reality Testing". 
the issue will be done when  "Reality Testing" ends (3/7). 

## Issue Details 

**Title:** "[Final] Bug in ________  "

**Content:** 

- What  is the bug? 

Your best strategy here, is to place a section to the wiki page you write, in which the bug is descriped.
When the bug is solved. This section wil be updated.

- What  is the scenario you did in order to find the bug?  

for example: 
1. I opened app on browser.
2. I pressed on hamburger button.
3. there is no logout.

Place this in our wiki page.

- Which  platform did you use for running the project (linux/windows/android)?

- Additional information 

##  Notes:

- Please label those issues with _"Final"_ 🏷  label and _"Bug"_  :label: label. 

- Please check there isn't an open issue about this bug already. 

- Please try to be specific. 
   for example, if you open an issue and tell us there is "Bug in map" we can't know what is the bug. 
   but if the issue is about "Bug - unexpected behaviour when loading map with no internet connection" 
   we clearly know what is the bug.  

- It will be helpful if you provide us pictures of the bug - for example, 
browser:

![](http://i.imgur.com/6qLL4P1.png)

javaScript console: (right click on the browser -> choose 'inspect' -> console)

![](http://i.imgur.com/G9sdkbX.png)

ionic console:

![](http://i.imgur.com/4KZViIt.png)

**Comment by yossigil** [comment]
Change reality testing to  "final"

**Comment by zahimizrahi** [comment]
Done. 🐳 
I thought you were referring to this term: https://en.wikipedia.org/wiki/Reality_testing

**Comment by yossigil** [comment]
NO. I just comply with @TomPalny's guidelines on labels. I enjoyed the link
