### ISSUE TITLE
Add Icons to buttons 

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#12]
_From @Shahar-Y on January 16, 2017 8:54_

As @zahimizrahi  suggested, we will add some cool designed buttons for the GUI screens using the free software inconion. 

@zahimizrahi, make it beautiful :neckbeard: 

https://www.youtube.com/watch?v=eAfyFTzZDMM

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement#115_

**Comment by shaysegal** [comment]
_From @DavidCohen55 on January 16, 2017 22:3_

@zahimizrahi it was my idea, and also the software I suggested 😠





Just kidding 😆 do a good job 👍

**Comment by shaysegal** [comment]
_From @zahimizrahi on January 18, 2017 13:56_

here, take your applause 👏 👏 👏

**Comment by shaysegal** [comment]
_From @ortroyaner on January 22, 2017 15:18_

Where do you get the icons? Can you please share?

**Comment by shaysegal** [comment]
_From @zahimizrahi on January 22, 2017 15:25_

http://iconion.com/ @ortroyaner

**Comment by zahimizrahi** [comment]
This was made during the refactoring in issue #16. Issue is closed.
