### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartParking#122]
making a user manual so the users can see it and learn how to work with the app

**Comment by zahimizrahi** [comment]
I dedicate this song for you: @DavidCohen55 
https://www.youtube.com/watch?v=byYBGEE8NCM 

❤️

**Comment by shaysegal** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10218409-204257602_3-s4-v1.png?transparent=1&palette=1&width=246) @zahimizrahi
