### ISSUE TITLE
How do i instal node.js?

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartParking#124]

**Comment by sefialbo** [comment]
Download it from: https://nodejs.org/en/

**Comment by noamyft** [comment]
and then what?

**Comment by noamyft** [comment]
You forgot to write to install curl.
(I didn't have that)

**Comment by sefialbo** [comment]
You don't have to use curl, but it's one option.

**Comment by tonylekhtman** [comment]
what do you do after downloading the tar.xz?

**Comment by noamyft** [comment]
i search how to install nodejs
i found the command with curl

But now i already installed that. i'm in step 6

**Comment by sefialbo** [comment]
if you are on windows just download the .exe and install it.
 on Ubuntu, one way is to use curl :
 
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

more infor here:
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
