### ISSUE TITLE
the text on the buttons is getting cut

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartParking#127]
the text on the buttons is getting cut so I don't know what each button does

**Comment by sefialbo** [comment]
Please show screen

**Comment by yaelAmitay** [comment]
it's from the android

**Comment by sefialbo** [comment]
We can't understand the bug, maybe take a photo with your phone then post here.

**Comment by yaelAmitay** [comment]
![image](https://user-images.githubusercontent.com/23058068/27769162-75e16b64-5f2c-11e7-88fc-94234f20f1cc.png)

**Comment by sefialbo** [comment]
Yes it's a bug, try using bigger screen, we have tablets if you want.

**Comment by zahimizrahi** [comment]
The application doesn't  have support of all resolutions.
