### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yuvalsimon** [TechnionYP5777/SmartParking#128]
I get this error:
![image](https://user-images.githubusercontent.com/17455055/27769067-29248c04-5f2a-11e7-939b-609cf36c4021.png)
In the previous installation step I got this:
![image](https://user-images.githubusercontent.com/17455055/27769071-3fd97950-5f2a-11e7-911a-0d0f730dbf57.png)

**Comment by sefialbo** [comment]
try to go to SmartParking/client and run again , also be sure that the NPM install you gonna do next will be in client too

**Comment by yuvalsimon** [comment]
Solved the package.josn error, still gives unmet dependencies (the ones in red above) if it should matter to me later..

**Comment by sefialbo** [comment]
it doesn't matter.
