### ISSUE TITLE
Add sound on pressing buttons

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#13]
_From @Shahar-Y on January 16, 2017 8:53_

When pressing a button in the GUI, we want it to make a sound on click.
For now, it is NIT for the current sprint.

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement#114_

**Comment by zahimizrahi** [comment]
it's an issue left from the last semester, it's not "nice to have" anymore since we move to Ionic, so there is no value to changing the current GUI if we will  start doing different one in the next weeks. 

Issue is closed.
