### ISSUE TITLE
App is called demo in android installation screen

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/SmartParking#130]
![screenshot_20170702-134023](https://user-images.githubusercontent.com/7457420/27769159-6a1bba64-5f2c-11e7-87c8-855880a53d4d.png)

**Comment by zahimizrahi** [comment]
@sefialbo  @DavidCohen55  ?

**Comment by tonylekhtman** [comment]
Any updates?

**Comment by sefialbo** [comment]
No, it's nice to have feature.
