### ISSUE TITLE
[Final] Bug in login failed

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartParking#133]
login failed for some reason. it's said that car number or password is wrong but I checked a few time that I'm inserting the rigth password and username.

I logged in after sign up as:
username: yaeli
password: 1234
number car: 1234567

**Comment by sefialbo** [comment]
what is the username and password ?

**Comment by yaelAmitay** [comment]
username: yaeli
password: 1234
number car: 1234567

**Comment by zahimizrahi** [comment]
In order to fix your problems, please use the template I wrote over here: https://github.com/TechnionYP5777/SmartParking/issues/114
 
it will be helpful if you give us the scenario and screenshots of the problem...

**Comment by sefialbo** [comment]
@yaelAmitay 
Please try and register again, the account is not the system. 
maybe there was an internet problem, or it was because of @zahimizrahi commit.

**Comment by zahimizrahi** [comment]
do git pull @tonylekhtman  @yuvalsimon  @noamyft  @yaelAmitay

**Comment by sefialbo** [comment]
@yaelAmitay try with differnet carNumber. There is already an account with this carNumber, you should get an alert "user already exist".

**Comment by yaelAmitay** [comment]
@zahimizrahi  did you publish a new apk?

**Comment by yaelAmitay** [comment]
@sefialbo  It didn't told me that the sign up failed

**Comment by yaelAmitay** [comment]
It tells me that I'm not connected to the internet but I am.
And it also tell me that after awhile and not when I'm clicking on "sign in"

**Comment by zahimizrahi** [comment]
it is because it took you too long to sign in, maybe your internet connection is slow...

**Comment by yaelAmitay** [comment]
okey I'll try signing up again, thank you
