### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yuvalsimon** [TechnionYP5777/SmartParking#134]
in step 9 in the installation wiki, running `npm run idme` gives error:
![image](https://user-images.githubusercontent.com/17455055/27769408-405b9c30-5f31-11e7-9377-c0f0f32e77e9.png)
I work on Windows and it looks like bash script (there is `rm` command) so maybe this is the reason, but until there the wiki supported Windows as well.

**Comment by zahimizrahi** [comment]
you did `echo "" > identity.js` first?
you run this command on client folder?

**Comment by yuvalsimon** [comment]
@zahimizrahi Should write in the installation instructions that you need bash in step 9 (you don't have it in windows by default). Google _shell.w32-ix86_. It worked after adding this to environment variable

**Comment by shaysegal** [comment]
in the requirement we wrote u need git bash...
