### ISSUE TITLE
[Final] Problem while registring

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartParking#135]
I am trying to register, and nothing happen.
When things happens it wrote:
![login bug](https://user-images.githubusercontent.com/18020768/27769437-bd44e4ae-5f31-11e7-8074-54ddbe23c961.png)

**Comment by yaelAmitay** [comment]
for me too

**Comment by Shahar-Y** [comment]
![image](https://user-images.githubusercontent.com/23077804/27787348-1a6ed41c-5fed-11e7-90d9-bee00298d268.png)

**Comment by Shahar-Y** [comment]
But seriously, check your internet connection and try again.
Maybe try connecting with a wire.
Tell me if the problem continues
The system works with a timer, and if you don't  get a response within 15 seconds, it shows this error.

**Comment by Shahar-Y** [comment]
Is it ok now?
