### ISSUE TITLE
More consistent messages

### ISSUE THREAD

**Issue by yuvalsimon** [TechnionYP5777/SmartParking#137]
When entering a car number that already exists the error message says the user already exists so it seems to relate to the username field.

**Comment by Shahar-Y** [comment]
Working on it

**Comment by yuvalsimon** [comment]
Another inconsistent message - after logging in, when editing details, the user can change the car number to any number (including already registered numbers) and the fields are not checked like in the registration. Also it does not show the edited details when opening again the details editing window

**Comment by Shahar-Y** [comment]
I pushed a commit. Please approve.
