### ISSUE TITLE
Not enough verbosity on register error

### ISSUE THREAD

**Issue by RoeiRaz** [TechnionYP5777/SmartParking#139]
When trying to register a user with existing username / email, there is no indication if the username is already taken or the email is already taken. It's not critical, but it would be much more convenient for the users if such functionality existed.
(I'm using the latest version of the android application)

**EDIT**: after browsing through the issues, it seems like a duplicate of #137

**Comment by zahimizrahi** [comment]
Hi roei, 
In our system, we chose only the car number to be key. 
You can register with the same email and the same username as long as your car number is different.
We did it because of the "customer game" some reviews was about it, that user can have some different cars.

**Comment by RoeiRaz** [comment]
Thanks!
