### ISSUE TITLE
sending/receiving notification email

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#14]
_From @DavidCohen55 on December 3, 2016 10:10_

Will be done in the this sprint:
1. send notification to specific user
2. receive notification to specific user

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement#40_

**Comment by shaysegal** [comment]
_From @zvili on December 14, 2016 8:14_

@DavidCohen55 : Define assignee & milestone

**Comment by shaysegal** [comment]
_From @yossigil on December 14, 2016 9:53_

indeed...

**Comment by shaysegal** [comment]
_From @DavidCohen55 on December 14, 2016 17:21_

@zvili @yossigil 
I'm sorry that I didn't do this before, I thought that I already assigned myself.
and about the milestone I didn't knew the date for this, for now it will be to the end of the semester until there will be a better milestone

**Comment by shaysegal** [comment]
_From @zvili on December 15, 2016 7:28_

The milestone for the end of the semester is "Sprint 2"

**Comment by shaysegal** [comment]
_From @DavidCohen55 on December 17, 2016 11:17_

@zvili the milestone was 4.7.17 because this issue isn't intent to be for this sprint, but to another sprint in the future
It doesn't mean that this will be due for 4.7.17, it was like this because there isn't a sprint for this yet

**Comment by shaysegal** [comment]
_From @sefialbo on January 18, 2017 11:11_

After discussions with @DavidCohen55 , we decided to leave "notification to all users which their parking slot will be expired" to the next sprint.

**Comment by zahimizrahi** [comment]
it's not relevant anymore (it's from the previous semester). Issue is closed.
