### ISSUE TITLE
Alert on starting

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/SmartParking#140]
Starting for the first time:
![Imgur](http://i.imgur.com/CH1dYR4.png)

Some alert appeared after pressing the button the app shut.

**Comment by RoeiRaz** [comment]
This bug also occurs on my device

**Comment by sefialbo** [comment]
We are aware of this bug, reopening the app should solve the issue. 
Also check that your location services are on.

**Comment by shaysegal** [comment]
worked? @RoeiRaz @tonylekhtman

**Comment by tonylekhtman** [comment]
Sometimes it works and sometimes not :(
My location services are turned on.
I got a black screen after one start up

**Comment by shaysegal** [comment]
backlogged
