### ISSUE TITLE
Inconsistency in the installation instruction 

### ISSUE THREAD

**Issue by RoeiRaz** [TechnionYP5777/SmartParking#141]
In the instructions for browser users, you state that Maven is not a requirement for regular users, but it seems like in stage (3) you instruct the users to run `mvn install` (which requires Maven)

**Comment by DavidCohen55** [comment]
Thank you for the notice,
We will mark this stage as a developer stage, and regular users doesn't need to do it 👍

**Comment by shaysegal** [comment]
Fixed ! ![bitmoji](https://render.bitstrips.com/v2/cpanel/9941638-204257602_3-s4-v1.png?transparent=1&palette=1&width=246)
