### ISSUE TITLE
No indication of parking slot place

### ISSUE THREAD

**Issue by yuvalsimon** [TechnionYP5777/SmartParking#142]
When clicking _FREE PARKING SLOT_ the message says there is a free parking slot. There is some tag in the map but it was there from the beginning and also when logging out and then logging in again so I'm not sure if it is the parking slot. Also the navigation never lets me press _GO_, but maybe it's related to this bug? 
(I'm using the web)

**Comment by shaysegal** [comment]
ok , the marker you the marker you talk is your current location and that's why he was there before, we the free parking button clear the parking the user is associate with ,if you want to check indication for this functionality you can check it in my detail page to see if there is parking slot associate with your user

**Comment by shaysegal** [comment]
can you explain what you mean by "never lets me press GO" (please also write  you car number and pass so i could recreate it) @yuvalsimon

**Comment by yuvalsimon** [comment]
Car number is 1231231, password is 1234. The _GO_ button in the navigate window is always off. I tried to enter addresses in both english and hebrew but I'm not sure what I have to write there in source and destination fields

**Comment by zahimizrahi** [comment]
it's a searchbar with autocomplete.
for example, if you type "c" you will see all the location our application supports that starts with C.

**Comment by yuvalsimon** [comment]
@zahimizrahi Alright it works, but should write these instructions there

**Comment by shaysegal** [comment]
from User Manual 
![image](https://user-images.githubusercontent.com/15847157/27789260-85456fec-5ff4-11e7-958a-53750093d0b4.png)
