### ISSUE TITLE
How does the simulation work?

### ISSUE THREAD

**Issue by tonylekhtman** [TechnionYP5777/SmartParking#146]
I started the simulation and it didn't do anything diffrent. :(

**Comment by shaysegal** [comment]
you correct there is no documentation about it (our fault.. )
you need to start tapping on the screen , you'll see the current location marker start following you , and when you'll get close enough to the end of the path you'll get a message about it

**Comment by shaysegal** [comment]
also it worked more easily on the browser there it will be easier to check it there

**Comment by tonylekhtman** [comment]
I'm sure, but sadly I have no chance to install the web version in time :(

It works kind of weird on mobile but the voice support is cool.

**Comment by shaysegal** [comment]
great! also I updated to wiki
