### ISSUE TITLE
When update details

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartParking#147]
I can change to invalid email, car number and phone number
Also, the stick is undefined

![screenshot from 2017-07-03 13-39-56](https://user-images.githubusercontent.com/18020768/27789457-5778826a-5ff5-11e7-8525-b46bcc332e45.png)

![screenshot from 2017-07-03 13-44-30](https://user-images.githubusercontent.com/18020768/27789574-cf365386-5ff5-11e7-8ecd-b48de821afd6.png)

**Comment by zahimizrahi** [comment]
thank you.
@DavidCohen55  @Shahar-Y ?

**Comment by Shahar-Y** [comment]
Working on it

**Comment by Shahar-Y** [comment]
Is it fixed?
