### ISSUE TITLE
Error in Navigate

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartParking#150]
I get this error after I click on navigation:
I sign in and it told me that the signing was success
![image](https://user-images.githubusercontent.com/23058068/27789928-fddb2800-5ff6-11e7-8126-0602ba0cdd67.png)

**Comment by sefialbo** [comment]
We don't know this error, can you try in chrome ? 
Also how to reproduce ?

**Comment by yaelAmitay** [comment]
I tried in chorme and it's working, thank you
