### ISSUE TITLE
Free parking slot

### ISSUE THREAD

**Issue by noamyft** [TechnionYP5777/SmartParking#152]
I logged on the system and press free parking slot, but i didnt take any.
the system tells me that i'm free go to. its weird..

![screenshot from 2017-07-03 14-04-04](https://user-images.githubusercontent.com/18020768/27790494-50728764-5ff9-11e7-9964-47a714321859.png)

**Comment by sefialbo** [comment]
It's a default alert , even if you didn't have a parking slot, we still check that.
