### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#18]
Here we'll maintain all the informations about our meetings. 
Each meeting will be documented with a protocol that one of us will write. 

**Next meeting:** Sunday 26.3 12:30 @SSDL Lab

**Comment by yossigil** [comment]
term is minutes, rather than protocol

**Comment by TomPalny** [comment]
Architecture change: Ionic - one platform to rule them (mobile) all
Wiki pages: 1. standards 2. testing (how we're testing + instructions for users on how to test) 3. "Install me" - maven, prerequisites etc. for proper installation of project
Critical bugs: map - assigned to Sefi & Shay
Test coverage: David
Gui continued: Zahi
Ionic learning: Shahar & David
Exception logging: Shahar

Milestone 1:
Navigation: instructions on navigation (visual navigation instructions)
Transition to Ionic
Changing maps database from the google DB to "In House", smarter database and make better walking decision.
Login options: recover password via email/sms 
Create several user levels: basic user, higher level user that can find parking for multiple cars and guests

**Comment by zahimizrahi** [comment]
Next meeting: Monday 3.4 13:30 @SSDL Lab

**Comment by shaysegal** [comment]
meeting summery:

- follow up on the work done last week
- decision the concentrate on make the iconic work since, all the gui (including map) dependent on that.
- codecov and code conventions wiki suppose to be uploaded this week .

**Comment by zahimizrahi** [comment]
Next meeting: Sunday 7.2 12:30 @ Taub 4th Floor

**Comment by zahimizrahi** [comment]
**Summary 7.5:** 

- Server problems @DavidCohen55  & @Shahar-Y : Try to solve the 'POST' problem. If you have difficulties with that, you can ask @AdiOmari  for help. 

- 3D Navigations:  Ullman Building is already set up this way in Google Maps. we need to do this for all the buildings in the Technion. Right now it's on hold, since we want to focus on Spring 1 goals.

- Map: Fix the default zoom to Technion area @shaysegal 
- Visibility: make the Map as homepage (myself) 
- Considerations of Shortest time, dynamic change of paths needs to be done @sefialbo 
- Changing the radio button on map

**Comment by zahimizrahi** [comment]
Meeting 04/06 -  Division of work roles for the following sprint:

- GUI continued: me 

- Map zoom-in @sefialbo  / @DavidCohen55 (?)

- Fix login & register & user details @Shahar-Y 

- 3D navigation @DavidCohen55  / @sefialbo (?)

- Logging @Shahar-Y 

- Fix maven builds: me 

- Vocal navigation @sefialbo 

- Simulation for navigation @shaysegal 

- Upload sprintboot to heroku app @DavidCohen55 

- Save recent queries @shaysegal 

- Feedback from register @Shahar-Y 

- Forget password functinality @Shahar-Y 

- Continuous Integration: me

It's an equal division, consideration the complexity of each mission. 

Some notes:

- We decided only one member will be in charge of each mission, not 2 working together (for quick progress). 
- **Large mission should be divided to smaller issues.**

**Comment by zahimizrahi** [comment]
no more meetings for this semester 🙈
