### ISSUE TITLE
Moving the project to Ionic

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartParking#21]
We were asked to use Ionic for our project. Ionic is an open source SDK for developing mobile apps, both for Android and IOS. @DavidCohen55 and myself were assigned for this issue. 
All progress will be documented here, and when the process is completed, a Wiki page will be opened with instructions of the installation process.

**Comment by Shahar-Y** [comment]
During the last week, David and I have read manuals and tried installing Cordova (used for Ionic) on eclipse. but so far didn't make much progress. We are currently trying a different approach with a new manual we found, combined with @yaelAmitay's issue about ionic*.

*I'll use this opportunity to thank Yael for her help and her detailed manual, which we are currently reading. kudos and stuff 👍

**Comment by Shahar-Y** [comment]
Update:
We have successfully installed ionic to my computer, with help from Yael. 
The next step is understanding the implications of ionic on our progress with the project, and starting to integrate it into the project. 
@zahimizrahi was also tagged, as it directly influences his work in the GUI part.
Link to Yael's issue: https://github.com/TechnionYP5777/SmartCity-Accessibility/issues/223
Link to the installation guide in ionic's website: http://ionicframework.com/docs/guide/installation.html

**Comment by TomPalny** [comment]
Nice progress, and good cooperation with Yael!

**Comment by Shahar-Y** [comment]
I found a tutorial in youtube which seems to be intuitive to understand. I suggest Zahi & David watch it:
https://www.youtube.com/watch?v=0jamhGf-8ww&list=PLYxzS__5yYQljbuGjaeugpqs9U07gS5P5

**Comment by Shahar-Y** [comment]
A comfortable way for working with the ionic-related files is Sublime Text. 
Download here: https://www.sublimetext.com
So far, it worked just fine for me

**Comment by shaysegal** [comment]
@zahimizrahi @Shahar-Y @DavidCohen55  found kind of IDE in ionic web site for building the GUI 
https://creator.ionic.io/app/dashboard/projects

**Comment by Shahar-Y** [comment]
I forgot to mention here that I created a wiki page about Ionic and the installation: https://github.com/TechnionYP5777/SmartParking/wiki/Ionic

**Comment by DavidCohen55** [comment]
### Summary of our progress:
@Shahar-Y and I spent the last few weeks working on ionic and figuring out how it works, 
we worked with @yaelAmitay's issue about Ionic which helped us to understand the platform, thank you very much 👏👏👏, and also with some online manuals.
As you can see now @zahimizrahi already started to work on making a GUI using it, you can see his progress in issue #32.
The next step is understanding how to connect the java logic to the ionic, Shahar and I will be in charge of it and will continue @shaysegal's issue #34.
We will continue our progress in relevant issues so we could do it in more convenient way.
