### ISSUE TITLE
Integrating CodeCov to our project 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#22]
CodeCov is a test coverage tool (similar to Eclemma we used last semester).
This issue will deal with integrating CodeCov to our project in order to track the test coverage of our project.

**Comment by zahimizrahi** [comment]
after hard time trying to integrate it, it seems codeCov won't support our project (due to the use of lambda expressions and etc.)

for now, we will use Eclemma as coverage tool. @DavidCohen55  will explain about it in Test Coverge wiki (issue #22).

issue is closed.

**Comment by TomPalny** [comment]
let me know if you need any intervention on my end to enable Eclemma

בתודה,
תום
