### ISSUE TITLE
create map working with ionic

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#24]
since we decided to go with ionic we need to create new map working with google's javascript api.
will work according to yael's tutorial .

**Comment by shaysegal** [comment]
map work on local , wait till @Shahar-Y  and @DavidCohen55 will upload the ionic main part to integrate the map into it

**Comment by shaysegal** [comment]
map work on local , wait till @Shahar-Y and @DavidCohen55 will upload the ionic main part to integrate the map into it

**Comment by shaysegal** [comment]
add example of template map, in order to make it work:
1. install ionic
2. in ionic_map directory do npm install
3. run it with the command ionic serve

**Comment by sefialbo** [comment]
map is working, including displaying markers and route. Other required features will be on other issues.
