### ISSUE TITLE
tests are failing 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#25]
Very urgent matter.
Tests are failing due to travis, as you can see here: https://travis-ci.org/TechnionYP5777/SmartParking

@DavidCohen55 , I assign you because you're in charge of this tests. :)

**Comment by DavidCohen55** [comment]
I'm working on this and it look weird, the tests worked last time I've checked.
I will see that each test file work and commit my progress 👍 
thanks for notifying me @zahimizrahi

**Comment by DavidCohen55** [comment]
something is not right, when I check each file exclusively the tests are working but when I try to do this separately the tests are failing, thoughts?
and moreover, the db start to store the "Test junk" (all of the new object we insert into the db) and don't delete them at the end like it suppose too (happens only when I try to run them all together).

**Comment by DavidCohen55** [comment]
All of the tests are working now and we can see that the travis compiled correctly while including them in the build, we can close this issue 😄
