### ISSUE TITLE
Making a presentation

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartParking#28]
We need to make a presentation for the 23.4 meeting.
I've sent a link for the google slides so everybody can contribute to it, you can find it in your mail.

let's do our best 😄

**Comment by TomPalny** [comment]
You forgot to add in the presentation the "one more thing..." (in the style of Steve Jobs presentations) feature we talked about in our last meeting before passover : *indoor* navigation, or 3D navigation. In other words, the navigation in the technion's buildings needs to include the multiple exits of buildings that some are important to navigate in the shortest path. For example, if I'm arriving from the Civil engineering building, going to the upper Taub parking, I need to go from the lobby entrance and go to the 2nd floor exit. So, when a user enters a building, the map of the building needs to pop up, just like you see when you go into the Grand mall (you immediately get a map of the building with floor info)

**Comment by Shahar-Y** [comment]
Closing the issue
