### ISSUE TITLE
Weekly Log for Sefi Albo

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartParking#3]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by TomPalny** [comment]
Hi Sefi, please add what you did in the first week. If it is related to an issue from last semester, reference the issue, if it related to learning a new technology such as ionic, write it without an issue number. First week should be the "lighter" week, but still should include some work done. 
Don't forget to write for week 2 as well when you know what you're working on

**Comment by sefialbo** [comment]
## **Week 1** (20/3-26/3)

- I helped with migrating the project, and also fixed an issue with the git repository. On this week I am working on #20.

**Comment by sefialbo** [comment]
## **Week 2** (26/3-2/4)
- worked on fixing the map, issue: #20.

## **Week 3** (2/4-8/4)
- worked on the ionic map implementation: #24 
- worked on navigation for map including: routes for driving and walking and markers for 
parking slots, issue: #56 

On 8/4-17/4 - Passover vacation

## **Week 4** (17/4-23/4)
- wrote an Installation wiki page.
- I continued to implement map features on this issue: #31 , including: add directions panel for directions, and radius markers for parking slots.

**Comment by TomPalny** [comment]
Hi Sefi, 
please write in further detail what you are working on, and include the range of the dates of the week instead of "on this week". Don't forget to reference issues you're currently working on

**Comment by sefialbo** [comment]
Update for three weeks:

## **Week 5** (23/4-29/4)

- worked on #32 : integrating the map into the project and working on map features.
- fixing map issues and bugs (also on #32 ) 

## **Week 6** (29/4-5/5)

- worked on #35 , added a functional Choosing Page for the map. In this page
the user selects source and destination.

## **Week 7** (6/5-13/5)

- continued working on #35. Fixed the directions panel to show the directions.
- also worked on #58, connected the choosing page (choose source and destination) to the map page.

**Comment by sefialbo** [comment]
## **Week 8** (13/5-20/5)
- I helped to write location service for ionic #42 
- I Worked on the choosing destination page #40
- Fixed location service, and connected it to map #40 
- I Worked on Improving reading locations performance on #52 
- And also started working on recording a path, on #45

**Comment by sefialbo** [comment]
## **Week 9** (21/5-26/5)

- worked on implementing the record route feature #50 
- worked on drawing the suggested route on map #51  
- worked on finding closet parking slot #47 

## **Week 10 - Week off** (26/5-2/6)

## **Week 11 - Week off** (2/6-9/6)

**Comment by sefialbo** [comment]
## Week 12  (10/6-17/6)
- working on implementing the voice navigation feature #60

**Comment by sefialbo** [comment]
## Week 13  (18/6-24/6)

- finalize work on voice navigation feature #60 
- testing voice navigation on android and fixing bugs #66 
- add 3D navigation #67 
- add server support for 3D navigation #70
- use server call to get best parking slot #72 (before this, we were only choosing the best parking area not taking into account the user sticker color, other data)

**Comment by sefialbo** [comment]
## Week 14  (25/6-3/7)

- fix android configurations #86
- free parking slot when start navigate, added gui support also #84 
- worked on pages gets re-constructed when you use menu #87 
- add current location support #88
- disable voice on browser #99
- show walking directions #107
- fix for floor directions #107
- fix for voice navigation (no issue for that)
- fix bugs shown on android device #119
- worked on creating a unique id for each device #90
- handling deployment on android including release version, debug, and update apks daily.
