### ISSUE TITLE
Adding login functionality to GUI

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#37]
- adding login & reguster functionality to demo GUI (e.g, integrating the typeScript to our already-tested Java method). 
- test it, as needed.

It should be easy, since you have the java code of this functionality. Good luck! 💪

**Comment by zahimizrahi** [comment]
Please note that HTML5 provides local stoarge. with local storage, our application can store data locally within the user's browser (cookies, for instance).

You can read more about it here: https://www.w3schools.com/html/html5_webstorage.asp

**Comment by Shahar-Y** [comment]
Forgot to assign myself. Assigning now.

**Comment by DavidCohen55** [comment]
The title was changed because we used this issue for our learning of the services and now @Shahar-Y and I are working on other issues that include the writing pf the services.
@Shahar-Y already did the register on issue #43 .

**Comment by zahimizrahi** [comment]
Sorry, I had to reopen the issue. it doesn't seem like it's working,
Right now, when you're trying to login, it just adds new user to the DB and makes the database dirty.

It's not login functionality, right now it's like **bad** register functionality. 😞

**Comment by Shahar-Y** [comment]
@zahimizrahi I believe I fixed the problem in Edge browser. The problem with Chrome communicating within the local hosts still remains and needs to be taken care of in the near future. 
For now, can you confirm that the problem was solved on other browsers? 
If not, please give me the details of what exactly lead to the error or send me the log file.

**Comment by zahimizrahi** [comment]
after yours and @shaysegal  I think it's good for now. thanks for the changes 👍  👍  💋
