### ISSUE TITLE
BUG: Ionic GUI project doesn't run on some computers - Solved

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartParking#38]
While working on integrating our code and Zahi's GUI, @Shahar-Y and I found that his project doesn't run on some of the computers including ours. The reason wasn't clear and it was an urgent issue that had to be resolved.
We opened this issue so that everyone could see the cause of the problem, and how we solved it. 
First, when we tried to run the ionic project we needed to use these command lines so we can run the project on our browser:
- `npm install`
- `ionic serve`

We got the following warnings in the command line:
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ionic-angular@3.0.1 requires a peer of @angular/common@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/compiler@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/compiler-cli@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/core@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/forms@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/http@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/platform-browser@4.0.0 but none was installed.
npm WARN ionic-angular@3.0.1 requires a peer of @angular/platform-browser-dynamic@4.0.0 but none was installed.`

And this problem in the localhost:

![image](https://cloud.githubusercontent.com/assets/23057199/25698993/f6487572-30c9-11e7-8898-22dd251b8c95.png)

After some research we found out that the **ionic-angular** version was not up-to-date so we run the following command line `npm install ionic-angular@latest --save`

**Everyone please make sure that you are working with latest version of ionic-angular.**

**Comment by Shahar-Y** [comment]
All computers are up-to-date with the latest version so it is irrelevant. Closing issue.
