### ISSUE TITLE
Learning about SpringBoot web services

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartParking#39]
Our main mission is to learn how to work with REST web sercices. 
Now we are going to work on sending a web request that contains information (POST).
This issue will contain the progress of our work and we will write here about it.
Currently, we are using the **SpringBoot tutorial**: https://www.tutorialspoint.com/spring 
and a video tutorial from **Youtube**: https://www.youtube.com/playlist?list=PLqq-6Pq4lTTbx8p2oCgcAQGQyqN8XeA1x

**Comment by zahimizrahi** [comment]
Why wasn't this closed?

**Comment by Shahar-Y** [comment]
I think Zahi is right. It should have been closed a while ago. Closing.
