### ISSUE TITLE
Making a storing paths class

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/SmartParking#46]
This class will be needed for @sefialbo & @shaysegal part of work and I will use this class for issue #44 
Before writing the service for Ionic there are few things to do...
- [x] Make a Java class for paths
- [x] Make a Database class
- [x] Testing the Class

When this issue will be done I will continue issue #44

**Comment by DavidCohen55** [comment]
@sefialbo & @shaysegal, I've been wondering...
The root path should be returned when there is a source and destination, but what if they are stored in the database with the opposite direction like destination -> source? the path that will be found should be reversed not? like if we had a path like: 

> (s->1->2->3->d)

 and we send now that source=d and destination=s, we would like to get

> (d->3->2->1->s)

How should I store the path, which option do you think is the best?
1. 1 row that include two columns of paths (for each direction).
2. 1 row that only include one direction and if I will get an opposite direction I will reverse the path with code.
3. 2 rows in the database for each direction.

**Comment by sefialbo** [comment]
I think you should save only source->direction path to db.
Usually "source" will be "My Location" so it will be different for each user anyway.

**Comment by DavidCohen55** [comment]
I've understand from @shaysegal that the source will be one of the known destinations like "Ulman".
Because if not there will be a problem getting the information in the case that the user isn't in the same position as before...

**Comment by sefialbo** [comment]
Ok after talking to @shaysegal , we agreed that the only paths we will be saving are from
parking area to known location. So, we just need the path in one direction.
These details doesn't really matter to the service, because if in the future we will want opposite direction, we can just call the same function. Anyway, the service should not make any assumptions, it should receive list of points and store them. The logic, for choosing similar path based on source and destination will be decided in the next phase.

**Comment by DavidCohen55** [comment]
I think that this issue if finished, @sefialbo & @shaysegal please check that this is everything you need and then I will make the service.
The class test coverage is 91.2%
If everything is OK please close the issue 😄

**Comment by DavidCohen55** [comment]
@shaysegal as you can see I added the fields we've talked about and checked that everything is working correct, also now the class test coverage is 92.9%.
I think that the class is working fine and now I can continue to the services  👍.

Any future changes will be tagged with issue #44 because the class will be changed only if this will be necessary to the services 😃

**Comment by shaysegal** [comment]
Great David, please let me know when the services are ready so I'll continue the work on the navigation
