### ISSUE TITLE
Fix maven install 

### ISSUE THREAD

**Issue by zahimizrahi** [TechnionYP5777/SmartParking#54]
right now, in our customer game, there was a problem for some people with the maven.

the problem is that it starts to run all the tests in the project. they're very heavy and some of them are unstable, so I want to disable them from maven build for now.

**Comment by shaysegal** [comment]
also , please change the "mainClass" in the pom.xml from opening to the rest_test.Application , i think that then we won't need to open eclipse to run the project , only use mvn
