### ISSUE TITLE
Fixing Last Sprint's Bugs - Shahar

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartParking#59]
After the demo on 4.6 , we've come to realize there are several issues that need to be fixed:

- [x] Login page should transfer the user to the map page after logging in. Also, remove success popup- its redundant.
- [x] Register functionality should return feedback after the action - if all is good, say it, and if something is wrong- then show it.
- [x] After register, the user is automatically logged in.
- [x] After register, the user is transferred to the map page.
- [x] Logout functionality is missing. Add it.

**Comment by zahimizrahi** [comment]
I think you should seperate those to another issues: 
- Feedback on register
- Logout the functionality

all the other problems should stay in this issue.

**Comment by Shahar-Y** [comment]
It has been decided, that the user will be transferred to the About page afret login or register.

**Comment by Shahar-Y** [comment]
Register now returns feedback, and so, I allow myself to close this tiring issue. YAY :)
