### ISSUE TITLE
Coordination of Weeks Off

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartParking#6]
This issue will be used to coordinate the weeks that you choose to take a week off.
This semester, you are **required** to take two weeks off from the project, at your convenience. 
You can take them consecutively or separately, as long as they are a week, and not less. 

The only important thing is that you let others know about it in advance, and that you will not be coding or working on the project at that week. 

Please advise, you should try to time your weeks off in a way that it won't detract from or prevent others in doing their part in the code. 

(Disclaimer: Even during your chosen week off, if there is some **_major_** problem with a code you wrote, you might still be required to respond, either on GitHub issues, or Telegram)

# Table Of Vacations

**Sprint 0 & 1**

| Team Member     | Week 1 | Week 2 | Week 3 | Week 4 |  Week 5 |  Week 6 |  Week 7 |  Week 8 |  
| -----------------   | ------  | ------  | ------  | ------  | -------  |  -------  |  -------  |  -------  | 
| David Cohen       | ------  | ------  | ------  | ------  | ------  |  ------  |  ------  |  ------  | 
| Zahi Mizrahi        | ------  |  ------  | ------  | ------  |   ------  |  ------  | ------   | 🍹   |   
| Shay Segal          | ------  |  🍹   | ------  | ------  |  ------  |  ------  |  ------  |  ------  |  
| Sefi Albo             | ------  | ------  | ------  | ------  |   ------  |  ------  |  ------  |  ------  | 
| Shahar Yair          | ------  |  ------  | ------  | ------  |  ------  |  ------  |  ------  |  ------  | 

**Sprint 2** 

| Team Member     | Week 9 | Week 10 | Week 11 | Week 12 |  Week 13 |  
| -----------------   | ------  | ------  | ------  | ------  | -------  |  
| David Cohen       | 🍹   |  🍹  | ------ | ------  | ------  | 
| Zahi Mizrahi        | ------  |  ------  | 🍹  | ------  |   ------  |  
| Shay Segal          | ------  |  🍹   | ------  | ------  |  ------  |  
| Sefi Albo             | 🍹   |  🍹  | ------  | ------  |   ------  |  
| Shahar Yair          | 🍹   |  🍹   | ------  | ------  |  ------  |

**Comment by shaysegal** [comment]
I plan to take the second week of the semester (24.3-30.3) as my first week off since I have a presentation I need to present in a seminar on that week.
sorry for short notice , please tell me if there's any problem with that @TomPalny @zahimizrahi @DavidCohen55 @sefialbo @Shahar-Y @yossigil

**Comment by TomPalny** [comment]
All good as far as I'm concerned

**Comment by Shahar-Y** [comment]
Hi everyone, I'm planning on taking two weeks off th project for my seminar and NA midterm. 
It will be between 23.5-6.6. 🎆  
Shahar

**Comment by zahimizrahi** [comment]
Hi Team,
I'm going to take a week off during the 8th week of the project (19-26.5). 
I hope I won't leave some issues open during this time. If so, I'll keep you informed about what you need to do in my parts. 

Thanks,
Zahi

**Comment by DavidCohen55** [comment]
Hi team,
I want to inform everyone that I would like to take my weeks of at the 10 and 11 weeks for working on my Android project 🤖 28.5-11.6

**Comment by sefialbo** [comment]
Hi team,
I am going to take two weeks off: 26.5 - 9.6 (week 9 and 10)

**Comment by shaysegal** [comment]
Hi team , i will take my second week off : 6.6-12.6

**Comment by zahimizrahi** [comment]
Hi Team, 
I'm going to take my second week off: 16.6-23.6

**Comment by Shahar-Y** [comment]
No more weeks off. Goodbye, issue :(
