### ISSUE TITLE
findPark service doesn't working

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#80]
it returns "" instead of valid json

**Comment by shaysegal** [comment]
please hurry with solving it , it blocks significant part of my work

**Comment by sefialbo** [comment]
@shaysegal I checked the navigation and it's working, notice that:
- your user has "low" sticker number (try with 0)
- your user doesn't already have a parking slot (need to remove it manually with DB now)
- don't use "Current Location", it's not supported yet.
