### ISSUE TITLE
Bug in register: method stopped working.

### ISSUE THREAD

**Issue by Shahar-Y** [TechnionYP5777/SmartParking#81]
For some reason the register method stopped working.
I need to fix it. While I'm at it, I'll improve the register feedback (more than just a boolean answer).

**Comment by Shahar-Y** [comment]
I believe the last commit also fixed the problem there was wit register. 
@shaysegal please confirm after you upload the new version to heroku.

**Comment by shaysegal** [comment]
working , thanks shahar ! ! 👍
