### ISSUE TITLE
accelerate calculation of best parking

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#85]
for now it took about a minute to show the route , it needs to be faster.

**Comment by DavidCohen55** [comment]
The code works good, @sefialbo and I tried to run it this week and it works good.
I will try it again just in case...

**Comment by sefialbo** [comment]
@DavidCohen55 the code works but it's slow. I suggest to start with "parkingArea.getNumOfFreeSlots()",  you should just keep a counter at the db and update it.
