### ISSUE TITLE
configure and test the server

### ISSUE THREAD

**Issue by shaysegal** [TechnionYP5777/SmartParking#9]
include multiple task in it :
- [x] configure Keys for interact with the server
- [x] update connection test and test the connection 
- [x] create the new DB to the server and fill with data (@DavidCohen55)

**Comment by DavidCohen55** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212133-202779545_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by shaysegal** [comment]
**note:** made the change server locally in the test file because we still use the old one for the data, once we migrate the data to the new one the change of the server use can be done to the all project by change the configuration on DBManger.java
